"""add vocab_quiz_student tables

Revision ID: 0f604cbf8f2c
Revises: 37b334ba3fc8
Create Date: 2026-09-28 06:04:57.740342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f604cbf8f2c'
down_revision = '37b334ba3fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocab_quiz_student_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('item_order_json', sa.Text(), nullable=False),
    sa.Column('gate_version', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('in_progress', 'completed')", name='ck_vqss_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vocab_quiz_student_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocab_quiz_student_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('vocab_quiz_student_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=120), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.Integer(), nullable=True),
    sa.Column('correct_option', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['vocab_quiz_student_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'item_id', name='uq_vqsa_session_item')
    )
    with op.batch_alter_table('vocab_quiz_student_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocab_quiz_student_attempts_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocab_quiz_student_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocab_quiz_student_attempts_session_id'))

    op.drop_table('vocab_quiz_student_attempts')
    with op.batch_alter_table('vocab_quiz_student_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocab_quiz_student_sessions_user_id'))

    op.drop_table('vocab_quiz_student_sessions')
    # ### end Alembic commands ###
