"""add vocab_quiz tables (isolated, admin-only)

aprolabs 연구 사이트 schema_reading L4~L6 어휘 퀴즈 1차 이식 - 기존
bank_questions/quiz_questions/curriculum* 등 어떤 기존 테이블도 수정하지
않는다(diff 결과가 신규 테이블 5개뿐임을 `flask db migrate` 출력으로
확인). downgrade()는 이 5개 테이블만 제거하므로 기존 데이터에 영향 없음.

Revision ID: 37b334ba3fc8
Revises: 63723761586a
Create Date: 2026-09-28 00:20:42.956649

수정(2026-09-28): 원래 down_revision을 c3d4e5f6a7b8로 잘못 잡았었다 -
운영 서버에는 그 뒤로 e04b5513c0ba/d6cf3cef8abd/63723761586a 세 리비전이
이미 커밋 없이 직접 적용돼 있었고(운영 DB의 실제 head), 그 사실을 이번
단계에서 서버를 직접 조사해 발견했다. 세 파일을 원본 그대로(SHA-256
확인) 이 저장소에 추가하고, 이 마이그레이션의 down_revision을 실제
운영 head인 63723761586a로 수정했다 - 기존 세 파일의 upgrade/downgrade
내용은 한 글자도 바꾸지 않았다.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b334ba3fc8'
down_revision = '63723761586a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocab_quiz_contents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.String(length=120), nullable=False),
    sa.Column('lemma', sa.String(length=200), nullable=False),
    sa.Column('pos', sa.String(length=30), nullable=True),
    sa.Column('canonical_definition', sa.Text(), nullable=True),
    sa.Column('student_definition', sa.Text(), nullable=True),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('example_target_form', sa.String(length=300), nullable=True),
    sa.Column('batch_id', sa.String(length=120), nullable=True),
    sa.Column('source_version', sa.String(length=120), nullable=False),
    sa.Column('student_exposure', sa.Boolean(), nullable=False),
    sa.Column('public_ready', sa.Boolean(), nullable=False),
    sa.Column('hold_reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vocab_quiz_contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocab_quiz_contents_content_id'), ['content_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_vocab_quiz_contents_lemma'), ['lemma'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocab_quiz_contents_source_version'), ['source_version'], unique=False)

    op.create_table('vocab_quiz_pilot_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(length=120), nullable=False),
    sa.Column('pilot_key', sa.String(length=10), nullable=False),
    sa.Column('item_type', sa.String(length=40), nullable=False),
    sa.Column('source_content_id', sa.String(length=120), nullable=True),
    sa.Column('source_content_ids_json', sa.Text(), nullable=True),
    sa.Column('lemma', sa.String(length=200), nullable=True),
    sa.Column('pos', sa.String(length=30), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=True),
    sa.Column('correct_option', sa.Integer(), nullable=True),
    sa.Column('public_payload_json', sa.Text(), nullable=True),
    sa.Column('answer_payload_json', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source_version', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('item_hash', sa.String(length=64), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("pilot_key IN ('l4l5', 'l6')", name='ck_vqpi_pilot_key'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vocab_quiz_pilot_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocab_quiz_pilot_items_item_id'), ['item_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_vocab_quiz_pilot_items_pilot_key'), ['pilot_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocab_quiz_pilot_items_source_content_id'), ['source_content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocab_quiz_pilot_items_source_version'), ['source_version'], unique=False)

    op.create_table('vocab_quiz_content_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.String(length=120), nullable=False),
    sa.Column('vocab_level', sa.Integer(), nullable=False),
    sa.Column('target_grade_band', sa.String(length=50), nullable=True),
    sa.Column('level_status', sa.String(length=30), nullable=False),
    sa.Column('boundary_flag', sa.Boolean(), nullable=False),
    sa.Column('level_source', sa.String(length=60), nullable=True),
    sa.Column('level_version', sa.String(length=60), nullable=False),
    sa.Column('level_reason_json', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.CheckConstraint("level_status IN ('PROVISIONAL_AUTO', 'REVIEW_BOUNDARY')", name='ck_vqcl_level_status'),
    sa.ForeignKeyConstraint(['content_id'], ['vocab_quiz_contents.content_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'level_version', name='uq_vqcl_content_version')
    )
    with op.batch_alter_table('vocab_quiz_content_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocab_quiz_content_levels_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocab_quiz_content_levels_level_version'), ['level_version'], unique=False)

    op.create_table('vocab_quiz_pilot_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pilot_key', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('item_order_json', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("pilot_key IN ('l4l5', 'l6')", name='ck_vqps_pilot_key'),
    sa.CheckConstraint("status IN ('in_progress', 'completed')", name='ck_vqps_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vocab_quiz_pilot_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocab_quiz_pilot_sessions_pilot_key'), ['pilot_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocab_quiz_pilot_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('vocab_quiz_pilot_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=120), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.Integer(), nullable=True),
    sa.Column('correct_option', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['vocab_quiz_pilot_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'item_id', name='uq_vqpa_session_item')
    )
    with op.batch_alter_table('vocab_quiz_pilot_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocab_quiz_pilot_attempts_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocab_quiz_pilot_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocab_quiz_pilot_attempts_session_id'))

    op.drop_table('vocab_quiz_pilot_attempts')
    with op.batch_alter_table('vocab_quiz_pilot_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocab_quiz_pilot_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_vocab_quiz_pilot_sessions_pilot_key'))

    op.drop_table('vocab_quiz_pilot_sessions')
    with op.batch_alter_table('vocab_quiz_content_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocab_quiz_content_levels_level_version'))
        batch_op.drop_index(batch_op.f('ix_vocab_quiz_content_levels_content_id'))

    op.drop_table('vocab_quiz_content_levels')
    with op.batch_alter_table('vocab_quiz_pilot_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocab_quiz_pilot_items_source_version'))
        batch_op.drop_index(batch_op.f('ix_vocab_quiz_pilot_items_source_content_id'))
        batch_op.drop_index(batch_op.f('ix_vocab_quiz_pilot_items_pilot_key'))
        batch_op.drop_index(batch_op.f('ix_vocab_quiz_pilot_items_item_id'))

    op.drop_table('vocab_quiz_pilot_items')
    with op.batch_alter_table('vocab_quiz_contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocab_quiz_contents_source_version'))
        batch_op.drop_index(batch_op.f('ix_vocab_quiz_contents_lemma'))
        batch_op.drop_index(batch_op.f('ix_vocab_quiz_contents_content_id'))

    op.drop_table('vocab_quiz_contents')
    # ### end Alembic commands ###
