"""초기 모델

Revision ID: 4697b50deed2
Revises: 
Create Date: 2026-03-24 00:45:53.232490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4697b50deed2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('feature_essay', sa.Boolean(), nullable=True),
    sa.Column('feature_zoom', sa.Boolean(), nullable=True),
    sa.Column('feature_payment', sa.Boolean(), nullable=True),
    sa.Column('feature_cms', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('branch_id')
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branches_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('role_level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('profile_image', sa.String(length=500), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('branch_contracts',
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('contract_start', sa.Date(), nullable=False),
    sa.Column('contract_end', sa.Date(), nullable=True),
    sa.Column('royalty_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('revenue_share', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('monthly_fee', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contract_id'),
    sa.UniqueConstraint('branch_id')
    )
    op.create_table('content_items',
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('content_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('publish_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('revenue_records',
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('gross_amount', sa.Integer(), nullable=False),
    sa.Column('royalty_amount', sa.Integer(), nullable=False),
    sa.Column('monthly_fee', sa.Integer(), nullable=False),
    sa.Column('net_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('branch_id', 'period_year', 'period_month', name='uq_revenue_period')
    )
    with op.batch_alter_table('revenue_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revenue_records_branch_id'), ['branch_id'], unique=False)

    op.create_table('content_permissions',
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('granted_by', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.content_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('content_id', 'branch_id', name='uq_content_branch')
    )
    with op.batch_alter_table('content_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_permissions_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_permissions_content_id'), ['content_id'], unique=False)

    op.create_table('content_views',
    sa.Column('view_id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.content_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('view_id')
    )
    with op.batch_alter_table('content_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_views_content_id'), ['content_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_views_content_id'))

    op.drop_table('content_views')
    with op.batch_alter_table('content_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_permissions_content_id'))
        batch_op.drop_index(batch_op.f('ix_content_permissions_branch_id'))

    op.drop_table('content_permissions')
    with op.batch_alter_table('revenue_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revenue_records_branch_id'))

    op.drop_table('revenue_records')
    op.drop_table('content_items')
    op.drop_table('branch_contracts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_branch_id'))

    op.drop_table('users')
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branches_code'))

    op.drop_table('branches')
    # ### end Alembic commands ###
