"""add vocab_quiz_admin_reviews table

Revision ID: 4d83374ccc5f
Revises: 0f604cbf8f2c
Create Date: 2026-09-28 06:33:08.006650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d83374ccc5f'
down_revision = '0f604cbf8f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocab_quiz_admin_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.String(length=120), nullable=False),
    sa.Column('verdict', sa.String(length=30), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('reviewer_user_id', sa.String(length=36), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.Column('content_hash_at_review', sa.String(length=64), nullable=False),
    sa.Column('item_hashes_at_review_json', sa.Text(), nullable=False),
    sa.CheckConstraint("verdict IN ('APPROVED_CANDIDATE', 'NEEDS_FIX', 'HOLD')", name='ck_vqar_verdict'),
    sa.ForeignKeyConstraint(['content_id'], ['vocab_quiz_contents.content_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vocab_quiz_admin_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocab_quiz_admin_reviews_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocab_quiz_admin_reviews_reviewer_user_id'), ['reviewer_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocab_quiz_admin_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocab_quiz_admin_reviews_reviewer_user_id'))
        batch_op.drop_index(batch_op.f('ix_vocab_quiz_admin_reviews_content_id'))

    op.drop_table('vocab_quiz_admin_reviews')
    # ### end Alembic commands ###
