"""mileage and avatar

Revision ID: 63723761586a
Revises: d6cf3cef8abd
Create Date: 2026-03-27 02:45:11.792049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63723761586a'
down_revision = 'd6cf3cef8abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar_items',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('mileage_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('ref_type', sa.String(length=50), nullable=True),
    sa.Column('ref_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mileage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mileage_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mileage_logs_student_id'), ['student_id'], unique=False)

    op.create_table('student_avatar_inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['avatar_items.item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'item_id', name='uq_student_item')
    )
    with op.batch_alter_table('student_avatar_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_avatar_inventory_student_id'), ['student_id'], unique=False)

    op.create_table('student_avatars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('character', sa.String(length=100), nullable=False),
    sa.Column('equipped', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    with op.batch_alter_table('reading_mbti_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options', sa.JSON(), nullable=True))

    with op.batch_alter_table('reading_mbti_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scores', sa.JSON(), nullable=True))

    with op.batch_alter_table('reading_mbti_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('combo_description', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('full_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reading_style', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('speaking_style', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('writing_style', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tips', sa.JSON(), nullable=True))
        batch_op.alter_column('strengths',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('weaknesses',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mileage', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_column('mileage')

    with op.batch_alter_table('reading_mbti_types', schema=None) as batch_op:
        batch_op.alter_column('weaknesses',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('strengths',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('tips')
        batch_op.drop_column('writing_style')
        batch_op.drop_column('speaking_style')
        batch_op.drop_column('reading_style')
        batch_op.drop_column('full_description')
        batch_op.drop_column('combo_description')

    with op.batch_alter_table('reading_mbti_results', schema=None) as batch_op:
        batch_op.drop_column('scores')

    with op.batch_alter_table('reading_mbti_questions', schema=None) as batch_op:
        batch_op.drop_column('options')

    op.drop_table('student_avatars')
    with op.batch_alter_table('student_avatar_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_avatar_inventory_student_id'))

    op.drop_table('student_avatar_inventory')
    with op.batch_alter_table('mileage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mileage_logs_student_id'))
        batch_op.drop_index(batch_op.f('ix_mileage_logs_created_at'))

    op.drop_table('mileage_logs')
    op.drop_table('avatar_items')
    # ### end Alembic commands ###
