"""add lms assignment and progress tables

Revision ID: d6cf3cef8abd
Revises: e04b5513c0ba
Create Date: 2026-03-26 15:14:38.670321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6cf3cef8abd'
down_revision = 'e04b5513c0ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_package_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.package_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'package_id', name='uq_branch_package')
    )
    with op.batch_alter_table('branch_package_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branch_package_assignments_branch_id'), ['branch_id'], unique=False)

    op.create_table('student_package_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.package_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_package_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_package_assignments_student_id'), ['student_id'], unique=False)

    op.create_table('student_item_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['student_package_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['curriculum_items.item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'assignment_id', 'item_id', name='uq_student_assignment_item')
    )
    with op.batch_alter_table('student_item_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_item_progress_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_item_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_item_progress_student_id'))

    op.drop_table('student_item_progress')
    with op.batch_alter_table('student_package_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_package_assignments_student_id'))

    op.drop_table('student_package_assignments')
    with op.batch_alter_table('branch_package_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branch_package_assignments_branch_id'))

    op.drop_table('branch_package_assignments')
    # ### end Alembic commands ###
