"""LMS tables

Revision ID: e04b5513c0ba
Revises: c3d4e5f6a7b8
Create Date: 2026-03-26 14:37:00.767817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04b5513c0ba'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curricula',
    sa.Column('curriculum_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('curriculum_id')
    )
    op.create_table('packages',
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_ordered', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('package_id')
    )
    op.create_table('curriculum_items',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('curriculum_id', sa.String(length=36), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('option_group', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.curriculum_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    with op.batch_alter_table('curriculum_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curriculum_items_curriculum_id'), ['curriculum_id'], unique=False)

    op.create_table('package_curricula',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('curriculum_id', sa.String(length=36), nullable=False),
    sa.Column('curriculum_version', sa.Integer(), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.curriculum_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.package_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('package_curricula', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_curricula_package_id'), ['package_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_curricula', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_curricula_package_id'))

    op.drop_table('package_curricula')
    with op.batch_alter_table('curriculum_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curriculum_items_curriculum_id'))

    op.drop_table('curriculum_items')
    op.drop_table('packages')
    op.drop_table('curricula')
    # ### end Alembic commands ###
