"""첨삭 모델 추가

Revision ID: e45245804642
Revises: b9db68a1d6d2
Create Date: 2026-03-24 05:05:36.992633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45245804642'
down_revision = 'b9db68a1d6d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('essays',
    sa.Column('essay_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('correction_model', sa.String(length=20), nullable=False),
    sa.Column('teacher_guide', sa.Text(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=True),
    sa.Column('is_finalized', sa.Boolean(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('essay_id')
    )
    with op.batch_alter_table('essays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_essays_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_essays_status'), ['status'], unique=False)

    op.create_table('essay_versions',
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('essay_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('revision_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['essay_id'], ['essays.essay_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_table('essay_results',
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('essay_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=True),
    sa.Column('total_score', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('final_grade', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['essay_id'], ['essays.essay_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['essay_versions.version_id'], ),
    sa.PrimaryKeyConstraint('result_id'),
    sa.UniqueConstraint('essay_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('essay_results')
    op.drop_table('essay_versions')
    with op.batch_alter_table('essays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_essays_status'))
        batch_op.drop_index(batch_op.f('ix_essays_branch_id'))

    op.drop_table('essays')
    # ### end Alembic commands ###
